language: cpp
branches: big_refactor

install: 
 - wget https://github.com/LASzip/LASzip/releases/download/v2.2.0/laszip-src-2.2.0.tar.gz
 - tar -xzf laszip-src-2.2.0.tar.gz
 - ls
 - cd laszip-src-2.2.0
 - ./configure && make && sudo make install
 - cd ..
 - sudo ./travis_build_upgrade.sh
 - sudo apt-get install -y libproj-dev libboost-system-dev libboost-filesystem-dev libgdal-dev libgeos-dev 
 - sudo apt-get install -y liblas-dev liblas-c-dev liblas-bin libeigen3-dev 

script: 
 - mkdir makefiles
 - cd makefiles
 - cmake -DCMAKE_CXX_COMPILER=g++-5 ..
 - make
 - cd ../tests
 - ./run_tests.sh

  
