sudo: required
dist: trusty
language: cpp
branches: master

install: 
 - wget https://github.com/LASzip/LASzip/releases/download/v2.2.0/laszip-src-2.2.0.tar.gz
 - tar -xzf laszip-src-2.2.0.tar.gz
 - ls
 - cd laszip-src-2.2.0
 - ./configure && make && sudo make install
 - cd ..

 - wget http://download.osgeo.org/geos/geos-3.4.2.tar.bz2
 - tar xjf geos-3.4.2.tar.bz2
 - cd geos-3.4.2
 - ./configure && make && sudo make install
 - cd ..
 
 - sudo apt-get install -y python-software-properties
 - sudo add-apt-repository -y ppa:ubuntugis/ppa
# - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -y gcc-5 g++-5
 - sudo apt-get install -y libboost-system-dev libboost-filesystem-dev libcgal-dev 
 - sudo apt-get install -y libproj-dev libgdal-dev
 - sudo apt-get install -y liblas-dev liblas-c-dev liblas-bin libeigen3-dev 
 - sudo apt-get install -y qt5-default qtdeclarative5-dev

script: 
 - mkdir -p makefiles
 - cd makefiles
 - cmake -DCMAKE_CXX_COMPILER=g++-5 ..
 - make
 - cd ..

after_script:
 - cd tests
 - ./run_tests.sh

  
