sudo: required
dist: xenial
language: cpp
branches: big_refactor
install: 
 - wget https://github.com/LASzip/LASzip/releases/download/v2.2.0/laszip-src-2.2.0.tar.gz
 - tar -xzf laszip-src-2.2.0.tar.gz
 - ls
 - cd laszip-src-2.2.0
 - ./configure && make && sudo make install
 - cd ..
 - sudo apt-get install libproj-dev libboost-system-dev libboost-filesystem-dev libgdal-dev libgeos-dev 
 - sudo apt-get install liblas-dev liblas-c-dev liblas-bin  
before_script: 
  - mkdir makefiles
  - cd makefiles
  - cmake ..
script: make
after_script:
 - cd ../tests
 - ./run_tests.sh

  
